### ISSUE TITLE
Github Sign in

### ISSUE THREAD

**Issue by nsosio** [premAI-io/state-of-open-source-ai#81]
When signing in with GitHub to add a comment in a chapter I've got 404.

![image](https://github.com/premAI-io/state-of-open-source-ai/assets/5698130/8f7f393a-ee0e-4d4b-975b-31c7ebeea3ed)

**Comment by casperdcl** [comment]
this is caused by https://utteranc.es redirecting to `/chapter.html` (rather than `/chapter/` or `/chapter/index.html`).

Based on https://github.com/utterance/utterances/issues/474 this is due to `jupyter-book build --builder dirhtml` generating:

```html
<link rel="canonical" href=".../chapter.html" />
```

instead of:

```html
<link rel="canonical" href=".../chapter/" />
```

just reported in https://github.com/executablebooks/jupyter-book/issues/2066
